//
//  ListOrdersRouter.swift
//  CleanStore
//
//  Created by Pete Barnes on 3/17/19.
//  Copyright (c) 2019 Pete Barnes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListOrdersRoutingLogic {
    func routeToCreateOrder(segue: UIStoryboardSegue?)
    func routeToShowOrder(segue: UIStoryboardSegue?)
}

protocol ListOrdersDataPassing {
    var dataStore: ListOrdersDataStore? { get }
}

class ListOrdersRouter: NSObject, ListOrdersRoutingLogic, ListOrdersDataPassing {
    weak var viewController: ListOrdersViewController?
    var dataStore: ListOrdersDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    func routeToCreateOrder(segue: UIStoryboardSegue?) {
        let destinationVC = segue!.destination as! CreateOrderViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToCreateOrder(source: dataStore!, destination: &destinationDS)
        navigateToCreateOrder(source: viewController!, destination:
            destinationVC)
    }
    
    func routeToShowOrder(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowOrderViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowOrder(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "ShowOrderViewController") as! ShowOrderViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowOrder(source: dataStore!, destination: &destinationDS)
            navigateToShowOrder(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ListOrdersViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    func navigateToCreateOrder(source: ListOrdersViewController, destination: CreateOrderViewController) {
    }
    
    func navigateToShowOrder(source: ListOrdersViewController, destination: ShowOrderViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ListOrdersDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
    
    func passDataToCreateOrder(source: ListOrdersDataStore, destination: inout CreateOrderDataStore) {
    }
    
    func passDataToShowOrder(source: ListOrdersDataStore, destination: inout ShowOrderDataStore) {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.order = source.orders?[selectedRow!]
    }
}
