//
//  CreateOrderWorkerTests.swift
//  CleanStore
//
//  Created by Pete Barnes on 3/27/19.
//  Copyright (c) 2019 Pete Barnes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class CreateOrderWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CreateOrderWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCreateOrderWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCreateOrderWorker() {
        sut = CreateOrderWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
