//
//  ShowOrderPresenter.swift
//  CleanStore
//
//  Created by Pete Barnes on 3/17/19.
//  Copyright (c) 2019 Pete Barnes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderPresentationLogic {
    func presentSomething(response: ShowOrder.Something.Response)
}

class ShowOrderPresenter: ShowOrderPresentationLogic {
    weak var viewController: ShowOrderDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: ShowOrder.Something.Response) {
        let viewModel = ShowOrder.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
