//
//  ShowOrderModels.swift
//  CleanStore
//
//  Created by Pete Barnes on 3/17/19.
//  Copyright (c) 2019 Pete Barnes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowOrder {
    // MARK: Use cases
    
    enum GetOrder {
        struct Request {
        }
        struct Response {
            var order: Order
        }
        struct ViewModel {
            
            struct DisplayedOrder
            {
                var id: String
                var date: String
                var email: String
                var name: String
                var total: String
            }
            
            var displayedOrder: DisplayedOrder
        }
    }
}
