//
//  ShowOrderRouter.swift
//  CleanStore
//
//  Created by Pete Barnes on 3/17/19.
//  Copyright (c) 2019 Pete Barnes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowOrderRoutingLogic {
    func routeToEditOrder(segue: UIStoryboardSegue?)
}

protocol ShowOrderDataPassing {
    var dataStore: ShowOrderDataStore? { get }
}

class ShowOrderRouter: NSObject, ShowOrderRoutingLogic, ShowOrderDataPassing {
    weak var viewController: ShowOrderViewController?
    var dataStore: ShowOrderDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    func routeToEditOrder(segue: UIStoryboardSegue?) {
        let destinationVC = segue!.destination as! CreateOrderViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToEditOrder(source: dataStore!, destination: &destinationDS)
        navigateToEditOrder(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ShowOrderViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    func navigateToEditOrder(source: ShowOrderViewController, destination: CreateOrderViewController) {
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ShowOrderDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
    
    func passDataToEditOrder(source: ShowOrderDataStore, destination: inout CreateOrderDataStore)
    {
        destination.orderToEdit = source.order
    }
}
